name: Notion Task Linker

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

jobs:
  link_notion_task:
    name: Link Notion Task
    runs-on: ubuntu-22.04
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          notion_task=$(echo ${{ github.head_ref }} | perl -ne 'm%^([A-Za-z]+?-[\d]+)%; print $1')
          if ! test -z "$notion_task"; then
            echo "match=true" >> $GITHUB_OUTPUT
            echo "notion_task=$notion_task" >> $GITHUB_OUTPUT
          fi

      - name: update PR description
        if: steps.check-branch.outputs.match == 'true'
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq .body)
          gh pr edit ${{ github.event.pull_request.number }} --body  "Notion Task: https://www.notion.so/${{ inputs.workspace }}/${{ steps.check-branch.outputs.notion_task }}
          ---
          ${DESCRIPTION}"
